export default {
    SERVICE_TYPE_LIST_SUCCESS : 'SERVICE_TYPE_LIST_SUCCESS',
    SERVICE_TYPE_LIST_FAILURE : 'SERVICE_TYPE_LIST_FAILURE',

    SERVICE_LIST_SUCCESS : 'SERVICE_LIST_SUCCESS',
    SERVICE_LIST_FAILURE : 'SERVICE_LIST_FAILURE',

    USER_LIST_SUCCESS : 'USER_LIST_SUCCESS',
    USER_LIST_FAILURE : 'USER_LIST_FAILURE',

    SERVICE_PROVIDER_LIST_SUCCESS : 'SERVICE_PROVIDER_LIST_SUCCESS',
    SERVICE_PROVIDER_LIST_FAILURE : 'SERVICE_PROVIDER_LIST_FAILURE',

    BOOKED_SERVICE_LIST_SUCCESS : 'BOOKED_SERVICE_LIST_SUCCESS',
    BOOKED_SERVICE_LIST_FAILURE : 'BOOKED_SERVICE_LIST_FAILURE'
};
